Rough Documentation
COS301-SE-2023/Pronto pull request #8
Opened 2023-05-03 19:17 UTC by ShashinGounden

Added a rough version of the documentation - introduction, vision and objective, business need, scope.

2023-05-03 19:20 UTC, u20612894 approved these changes
Good start!

2023-05-04 08:03 UTC, Tymac15 approved these changes
Started working on this with you last night, good start and I see no isssues.

2023-05-05 03:35 UTC, Bandisa commented on .DS_Store
please remove the .DS_Store file and add it onto the git ignore.

2023-05-05 03:36 UTC, Bandisa commented on Documentation/Pronto_ Documentation.pdf
Look great so far. And thank you for adding the suggested layout change.

2023-05-05 07:19 UTC, u21598267 commented on .DS_Store
@ShashinGounden , use my .gitignore in frontend-misc. It has the .DS_Store included.

2023-05-05 07:47 UTC, ShashinGounden commented on .DS_Store
Will do

2023-05-05 18:03 UTC, ShashinGounden commented
For @u20612894 use case diagram for file uploads, I think you should specify the two cases of institutions uploading a lecture schedule and also uploading campus maps (i.e. with other use cases stemming from it). Same with updating files. 

With regard to "select activity" in the timetable generation, maybe one use case of selecting lecture and another for practical etc as use cases too?

Just double check that what I'm saying makes sense.

2023-05-05 18:19 UTC, Tymac15 reviewed
Updated the use case for user reg/authentication to include change password which extends edit account details.

2023-05-05 18:50 UTC, ShashinGounden reviewed
Looks good

2023-05-06 18:15 UTC, Bandisa commented on Documentation/timetable_generation_use_case.png
# Request
may we change `Select Practical` to `Select Activity` since the activities can be of different types such as tutorial and so on.

2023-05-06 18:17 UTC, Bandisa commented on Documentation/GeoLocationUseCase.jpg
# Request
can we change the name of this user case to one that is more specific to our use case, for an example `campus navigation` or any similar. Geolocation services is too broad of a name for this use case while we have one main intent for it.

2023-05-08 12:52 UTC, ShashinGounden commented on Documentation/GeoLocationUseCase.jpg
I agree with Bandisa. @u21598267 please update the naming of the use case, I will update the functional requirement.

2023-05-16 15:15 UTC, ShashinGounden reviewed
Looks good, make sure to add to documentation once all approved.

2023-05-16 15:52 UTC, Bandisa requested changes
Just a minor change request.

But everything else looks correct.

2023-05-16 15:52 UTC, Bandisa commented on Documentation/Pronto class diagram.jpg
Think institution should be actually named Admin, since that is what will be extended from the User type.
Then institution itself should be its own separate entity like courses, which will have the courses and so on. so:
User -> {Admin, Student, Lecturer}
Institution <has> {Admin (1), Lecturer(many), Student(many), Course(many)}

Think after this minor change it will be correct, cause right now it is implying that Institution is of type user, which is not necessarily true.

2023-05-16 16:56 UTC, Tymac15 commented on Documentation/Pronto class diagram.jpg
Changes made, good suggestion

2023-05-16 18:56 UTC, Bandisa requested changes

2023-05-16 18:56 UTC, Bandisa commented on Documentation/Pronto class diagram.jpg
Minor Change:
Institution has an admin, and the admin uploads files.

2023-05-16 19:12 UTC, Tymac15 commented on Documentation/Pronto class diagram.jpg
done

2023-05-17 07:39 UTC, u21598267 commented on Documentation/GeoLocationUseCase.jpg
- Use case has been corrected
- Subsystem is now Campus Navigation (Former name GeolocationServices)

2023-05-21 16:28 UTC, u20612894 approved these changes
Seems good

2023-05-21 16:28 UTC, Tymac15 approved these changes
ready to go

2023-05-21 16:28 UTC, merged